[book]
title = "typst-test"
description = "A guide and reference document for typst-test."
authors = ["tingerrr <tinger@tinger.dev>"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
git-repository-url = "https://github.com/tingerrr/typst-test"
