[package]
name = "typst-test"
repository = "https://github.com/tingerrr/typst-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typst-test-lib = { path = "../typst-test-lib" }

anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive"] }
bitflags.workspace = true
ecow.workspace = true
rayon.workspace = true
semver.workspace = true
serde.workspace = true
termcolor.workspace = true
tiny-skia.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tree.workspace = true
typst.workspace = true
typst-project.workspace = true
